-- Table: ipedsdata.ipeds_finance_data1

-- DROP TABLE IF EXISTS ipedsdata.ipeds_finance_data1;

CREATE TABLE IF NOT EXISTS ipedsdata.ipeds_finance_data1
(
    "UNITID" bigint,
    "XF1A01" text COLLATE pg_catalog."default",
    "F1A01" double precision,
    "XF1A31" text COLLATE pg_catalog."default",
    "F1A31" double precision,
    "XF1A04" text COLLATE pg_catalog."default",
    "F1A04" double precision,
    "XF1A05" text COLLATE pg_catalog."default",
    "F1A05" double precision,
    "XF1A06" text COLLATE pg_catalog."default",
    "F1A06" double precision,
    "XF1A19" text COLLATE pg_catalog."default",
    "F1A19" double precision,
    "XF1A07" text COLLATE pg_catalog."default",
    "F1A07" double precision,
    "XF1A08" text COLLATE pg_catalog."default",
    "F1A08" double precision,
    "XF1A09" text COLLATE pg_catalog."default",
    "F1A09" double precision,
    "XF1A10" text COLLATE pg_catalog."default",
    "F1A10" double precision,
    "XF1A11" text COLLATE pg_catalog."default",
    "F1A11" double precision,
    "XF1A12" text COLLATE pg_catalog."default",
    "F1A12" double precision,
    "XF1A13" text COLLATE pg_catalog."default",
    "F1A13" double precision,
    "XF1A20" text COLLATE pg_catalog."default",
    "F1A20" double precision,
    "XF1A14" text COLLATE pg_catalog."default",
    "F1A14" double precision,
    "XF1A15" text COLLATE pg_catalog."default",
    "F1A15" double precision,
    "XF1A16" text COLLATE pg_catalog."default",
    "F1A16" double precision,
    "XF1A17" text COLLATE pg_catalog."default",
    "F1A17" double precision,
    "XF1A18" text COLLATE pg_catalog."default",
    "F1A18" double precision,
    "XF1A214" text COLLATE pg_catalog."default",
    "F1A214" double precision,
    "XF1A224" text COLLATE pg_catalog."default",
    "F1A224" double precision,
    "XF1A234" text COLLATE pg_catalog."default",
    "F1A234" double precision,
    "XF1A324" text COLLATE pg_catalog."default",
    "F1A324" double precision,
    "XF1A274" text COLLATE pg_catalog."default",
    "F1A274" double precision,
    "XF1A27T4" text COLLATE pg_catalog."default",
    "F1A27T4" double precision,
    "XF1A284" text COLLATE pg_catalog."default",
    "F1A284" double precision,
    "XF1A334" text COLLATE pg_catalog."default",
    "F1A334" double precision,
    "XF1A344" text COLLATE pg_catalog."default",
    "F1A344" double precision,
    "XF1D01" text COLLATE pg_catalog."default",
    "F1D01" double precision,
    "XF1D02" text COLLATE pg_catalog."default",
    "F1D02" double precision,
    "XF1D03" text COLLATE pg_catalog."default",
    "F1D03" double precision,
    "XF1D04" text COLLATE pg_catalog."default",
    "F1D04" double precision,
    "XF1D05" text COLLATE pg_catalog."default",
    "F1D05" double precision,
    "XF1D06" text COLLATE pg_catalog."default",
    "F1D06" double precision,
    "XF1B01" text COLLATE pg_catalog."default",
    "F1B01" bigint,
    "XF1B02" text COLLATE pg_catalog."default",
    "F1B02" bigint,
    "XF1B03" text COLLATE pg_catalog."default",
    "F1B03" bigint,
    "XF1B04" text COLLATE pg_catalog."default",
    "F1B04" bigint,
    "XF1B04A" text COLLATE pg_catalog."default",
    "F1B04A" bigint,
    "XF1B04B" text COLLATE pg_catalog."default",
    "F1B04B" bigint,
    "XF1B05" text COLLATE pg_catalog."default",
    "F1B05" double precision,
    "XF1B06" text COLLATE pg_catalog."default",
    "F1B06" double precision,
    "XF1B26" text COLLATE pg_catalog."default",
    "F1B26" bigint,
    "XF1B07" text COLLATE pg_catalog."default",
    "F1B07" double precision,
    "XF1B08" text COLLATE pg_catalog."default",
    "F1B08" bigint,
    "XF1B09" text COLLATE pg_catalog."default",
    "F1B09" bigint,
    "XF1B10" text COLLATE pg_catalog."default",
    "F1B10" bigint,
    "XF1B11" text COLLATE pg_catalog."default",
    "F1B11" bigint,
    "XF1B12" text COLLATE pg_catalog."default",
    "F1B12" bigint,
    "XF1B13" text COLLATE pg_catalog."default",
    "F1B13" bigint,
    "XF1B14" text COLLATE pg_catalog."default",
    "F1B14" bigint,
    "XF1B15" text COLLATE pg_catalog."default",
    "F1B15" bigint,
    "XF1B16" text COLLATE pg_catalog."default",
    "F1B16" bigint,
    "XF1B17" text COLLATE pg_catalog."default",
    "F1B17" bigint,
    "XF1B18" text COLLATE pg_catalog."default",
    "F1B18" bigint,
    "XF1B19" text COLLATE pg_catalog."default",
    "F1B19" bigint,
    "XF1B27" text COLLATE pg_catalog."default",
    "F1B27" bigint,
    "XF1B20" text COLLATE pg_catalog."default",
    "F1B20" double precision,
    "XF1B21" text COLLATE pg_catalog."default",
    "F1B21" double precision,
    "XF1B22" text COLLATE pg_catalog."default",
    "F1B22" double precision,
    "XF1B23" text COLLATE pg_catalog."default",
    "F1B23" bigint,
    "XF1B24" text COLLATE pg_catalog."default",
    "F1B24" bigint,
    "XF1B25" text COLLATE pg_catalog."default",
    "F1B25" bigint,
    "XF1C011" text COLLATE pg_catalog."default",
    "F1C011" bigint,
    "XF1C012" text COLLATE pg_catalog."default",
    "F1C012" bigint,
    "XF1C021" text COLLATE pg_catalog."default",
    "F1C021" bigint,
    "XF1C022" text COLLATE pg_catalog."default",
    "F1C022" bigint,
    "XF1C031" text COLLATE pg_catalog."default",
    "F1C031" bigint,
    "XF1C032" text COLLATE pg_catalog."default",
    "F1C032" bigint,
    "XF1C051" text COLLATE pg_catalog."default",
    "F1C051" bigint,
    "XF1C052" text COLLATE pg_catalog."default",
    "F1C052" bigint,
    "XF1C061" text COLLATE pg_catalog."default",
    "F1C061" bigint,
    "XF1C062" text COLLATE pg_catalog."default",
    "F1C062" bigint,
    "XF1C071" text COLLATE pg_catalog."default",
    "F1C071" bigint,
    "XF1C072" text COLLATE pg_catalog."default",
    "F1C072" bigint,
    "XF1C101" text COLLATE pg_catalog."default",
    "F1C101" bigint,
    "XF1C111" text COLLATE pg_catalog."default",
    "F1C111" double precision,
    "XF1C112" text COLLATE pg_catalog."default",
    "F1C112" double precision,
    "XF1C121" text COLLATE pg_catalog."default",
    "F1C121" double precision,
    "XF1C122" text COLLATE pg_catalog."default",
    "F1C122" double precision,
    "XF1C131" text COLLATE pg_catalog."default",
    "F1C131" double precision,
    "XF1C132" text COLLATE pg_catalog."default",
    "F1C132" double precision,
    "XF1C141" text COLLATE pg_catalog."default",
    "F1C141" bigint,
    "XF1C142" text COLLATE pg_catalog."default",
    "F1C142" bigint,
    "XF1C191" text COLLATE pg_catalog."default",
    "F1C191" bigint,
    "XF1C192" text COLLATE pg_catalog."default",
    "F1C192" bigint,
    "XF1C193" text COLLATE pg_catalog."default",
    "F1C193" bigint,
    "XF1C19OM" text COLLATE pg_catalog."default",
    "F1C19OM" bigint,
    "XF1C19DP" text COLLATE pg_catalog."default",
    "F1C19DP" bigint,
    "XF1C19IN" text COLLATE pg_catalog."default",
    "F1C19IN" bigint,
    "XF1C19OT" text COLLATE pg_catalog."default",
    "F1C19OT" bigint,
    "F1MHP" bigint,
    "XF1M01" text COLLATE pg_catalog."default",
    "F1M01" double precision,
    "XF1M02" text COLLATE pg_catalog."default",
    "F1M02" double precision,
    "XF1M03" text COLLATE pg_catalog."default",
    "F1M03" double precision,
    "XF1M04" text COLLATE pg_catalog."default",
    "F1M04" double precision,
    "F1MHOP" bigint,
    "XF1M05" text COLLATE pg_catalog."default",
    "F1M05" double precision,
    "XF1M06" text COLLATE pg_catalog."default",
    "F1M06" double precision,
    "XF1M07" text COLLATE pg_catalog."default",
    "F1M07" double precision,
    "XF1M08" text COLLATE pg_catalog."default",
    "F1M08" double precision,
    "XF1E01" text COLLATE pg_catalog."default",
    "F1E01" double precision,
    "XF1E02" text COLLATE pg_catalog."default",
    "F1E02" double precision,
    "XF1E03" text COLLATE pg_catalog."default",
    "F1E03" double precision,
    "XF1E04" text COLLATE pg_catalog."default",
    "F1E04" double precision,
    "XF1E05" text COLLATE pg_catalog."default",
    "F1E05" double precision,
    "XF1E06" text COLLATE pg_catalog."default",
    "F1E06" double precision,
    "XF1E07" text COLLATE pg_catalog."default",
    "F1E07" double precision,
    "XF1E08" text COLLATE pg_catalog."default",
    "F1E08" double precision,
    "XF1E09" text COLLATE pg_catalog."default",
    "F1E09" double precision,
    "XF1E10" text COLLATE pg_catalog."default",
    "F1E10" double precision,
    "XF1E11" text COLLATE pg_catalog."default",
    "F1E11" double precision,
    "XF1E12" text COLLATE pg_catalog."default",
    "F1E12" double precision,
    "XF1E121" text COLLATE pg_catalog."default",
    "F1E121" double precision,
    "XF1E122" text COLLATE pg_catalog."default",
    "F1E122" double precision,
    "XF1E13" text COLLATE pg_catalog."default",
    "F1E13" double precision,
    "XF1E131" text COLLATE pg_catalog."default",
    "F1E131" double precision,
    "XF1E132" text COLLATE pg_catalog."default",
    "F1E132" double precision,
    "XF1E14" text COLLATE pg_catalog."default",
    "F1E14" double precision,
    "XF1E141" text COLLATE pg_catalog."default",
    "F1E141" double precision,
    "XF1E142" text COLLATE pg_catalog."default",
    "F1E142" double precision,
    "XF1E15" text COLLATE pg_catalog."default",
    "F1E15" double precision,
    "XF1E151" text COLLATE pg_catalog."default",
    "F1E151" double precision,
    "XF1E152" text COLLATE pg_catalog."default",
    "F1E152" double precision,
    "XF1E16" text COLLATE pg_catalog."default",
    "F1E16" double precision,
    "XF1E161" text COLLATE pg_catalog."default",
    "F1E161" double precision,
    "XF1E162" text COLLATE pg_catalog."default",
    "F1E162" double precision,
    "XF1E17" text COLLATE pg_catalog."default",
    "F1E17" double precision,
    "XF1E171" text COLLATE pg_catalog."default",
    "F1E171" double precision,
    "XF1E172" text COLLATE pg_catalog."default",
    "F1E172" double precision,
    "F1FHA" bigint,
    "XF1H01" text COLLATE pg_catalog."default",
    "F1H01" double precision,
    "XF1H02" text COLLATE pg_catalog."default",
    "F1H02" double precision,
    "XF1H03" text COLLATE pg_catalog."default",
    "F1H03" double precision,
    "XF1H03A" text COLLATE pg_catalog."default",
    "F1H03A" double precision,
    "XF1H03B" text COLLATE pg_catalog."default",
    "F1H03B" double precision,
    "XF1H03C" text COLLATE pg_catalog."default",
    "F1H03C" double precision,
    "XF1H03D" text COLLATE pg_catalog."default",
    "F1H03D" double precision,
    "XF1N01" text COLLATE pg_catalog."default",
    "F1N01" double precision,
    "XF1N02" text COLLATE pg_catalog."default",
    "F1N02" double precision,
    "XF1N03" text COLLATE pg_catalog."default",
    "F1N03" double precision,
    "XF1N04" text COLLATE pg_catalog."default",
    "F1N04" double precision,
    "XF1N05" text COLLATE pg_catalog."default",
    "F1N05" double precision,
    "XF1N06" text COLLATE pg_catalog."default",
    "F1N06" double precision,
    "XF1N07" text COLLATE pg_catalog."default",
    "F1N07" double precision
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS ipedsdata.ipeds_finance_data1
    OWNER to ipeds;